[build]
  command = "npm run build"
  publish = "dist"
  functions = "server/functions"

[dev]
    port = 8888
    functions = "server/functions"
    framework = "#auto"
    
[functions]
  [functions.max_duration]
    duration = 30
  external_node_modules = ["sequelize", "cors", "pg"]