[build]
  command = "npm run build"
  publish = "dist"
  functions = "server/functions"
  node_version = "22"

[dev]
    port = 8888
    functions = "server/functions"
    framework = "#auto"
    
[functions]
  node_bundler = "esbuild"
  esbuild_options = { format = "esm" }
  [functions.max_duration]
    duration = 60
  external_node_modules = ["sequelize", "cors", "pg"]